"""

Boilerplate dictionaries which the testing suite must use to verify NaNs are not showing up in the wrong places.

"""

# nan here means something is broken
NEVER_NAN = {
    "halo_data": [
        "properties/core/mass_total",
        "properties/core/velocity_dispersion_total",
        "properties/core/radius_r20_total",
        "properties/core/radius_half_mass_total",
        "properties/core/radius_r80_total",
        "properties/core/com_pos_total",
        "properties/core/com_vel_total",
        "properties/core/minpot_pos",
        "properties/core/minpot_vel",
    ],
    "galaxy_data": [
        "properties/core/mass_baryon",
        "properties/core/velocity_dispersion_baryon",
        "properties/core/radius_r20_baryon",
        "properties/core/radius_half_mass_baryon",
        "properties/core/radius_r80_baryon",
        "properties/core/com_pos_baryon",
        "properties/core/com_vel_baryon",
        "properties/core/BoverT_baryon",
        "properties/core/kappa_rot_baryon",
        "properties/environment/mass_total_30kpc",
    ],
}

# nan here should only occur if the group is empty
CONDITIONAL_NAN = {
    "halo_data": [
        (
            "n_total",
            [
                "properties/core/L_azimuth_total",
                "properties/core/L_elevation_total",
                "properties/core/L_total",
                "properties/core/inertia_tensor_total",
            ],
        ),
        (
            "n_baryon",
            [
                "properties/core/radius_r20_baryon",
                "properties/core/radius_half_mass_baryon",
                "properties/core/radius_r80_baryon",
                "properties/core/velocity_dispersion_baryon",
                "properties/core/L_azimuth_baryon",
                "properties/core/L_elevation_baryon",
                "properties/core/L_baryon",
                "properties/core/inertia_tensor_baryon",
            ],
        ),
        (
            "membership/gas_lengths",
            [
                "properties/core/radius_r20_gas",
                "properties/core/radius_half_mass_gas",
                "properties/core/radius_r80_gas",
                "properties/core/velocity_dispersion_gas",
                "properties/core/L_gas",
                "properties/core/L_azimuth_gas",
                "properties/core/L_elevation_gas",
                "properties/core/inertia_tensor_gas",
                "properties/particle_specific/metallicity_gas_mass_weighted",
                "properties/particle_specific/temperature_gas_mass_weighted",
            ],
        ),
        (
            "membership/star_lengths",
            [
                "properties/core/radius_r20_star",
                "properties/core/radius_half_mass_star",
                "properties/core/radius_r80_star",
                "properties/core/velocity_dispersion_star",
                "properties/core/L_star",
                "properties/core/L_azimuth_star",
                "properties/core/L_elevation_star",
                "properties/core/inertia_tensor_star",
                "properties/particle_specific/metallicity_star_mass_weighted",
                "properties/particle_specific/age_star_mass_weighted",
            ],
        ),
        (
            "membership/dm_lengths",
            [
                "properties/core/radius_r20_dm",
                "properties/core/radius_half_mass_dm",
                "properties/core/radius_r80_dm",
                "properties/core/velocity_dispersion_dm",
                "properties/core/L_dm",
                "properties/core/inertia_tensor_dm",
                "properties/core/L_azimuth_dm",
                "properties/core/L_elevation_dm",
            ],
        ),
        (
            "membership/bh_lengths",
            [
                "properties/core/radius_r20_bh",
                "properties/core/radius_half_mass_bh",
                "properties/core/radius_r80_bh",
                "properties/core/velocity_dispersion_bh",
                "properties/core/L_bh",
                "properties/core/inertia_tensor_bh",
                "properties/core/L_azimuth_bh",
                "properties/core/L_elevation_bh",
                "properties/particle_specific/smbh_mdot",
                "properties/particle_specific/smbh_fedd",
                "properties/particle_specific/smbh_mass",
            ],
        ),
    ],
    "galaxy_data": [
        (
            "n_baryon",
            [
                "properties/core/L_azimuth_baryon",
                "properties/core/L_elevation_baryon",
                "properties/core/L_baryon",
                "properties/core/radius_r20_baryon",
                "properties/core/radius_half_mass_baryon",
                "properties/core/radius_r80_baryon",
                "properties/core/velocity_dispersion_baryon",
                "properties/core/inertia_tensor_baryon",
            ],
        ),
        (
            "membership/gas_lengths",
            [
                "properties/core/radius_r20_gas",
                "properties/core/radius_half_mass_gas",
                "properties/core/radius_r80_gas",
                "properties/core/velocity_dispersion_gas",
                "properties/core/L_gas",
                "properties/core/inertia_tensor_gas",
                "properties/core/L_azimuth_gas",
                "properties/core/L_elevation_gas",
                "properties/core/BoverT_gas",
                "properties/core/kappa_rot_gas",
                "properties/particle_specific/metallicity_gas_mass_weighted",
                "properties/particle_specific/temperature_gas_mass_weighted",
            ],
        ),
        (
            "membership/star_lengths",
            [
                "properties/core/radius_r20_star",
                "properties/core/radius_half_mass_star",
                "properties/core/radius_r80_star",
                "properties/core/velocity_dispersion_star",
                "properties/core/L_star",
                "properties/core/inertia_tensor_star",
                "properties/core/L_azimuth_star",
                "properties/core/L_elevation_star",
                "properties/core/BoverT_star",
                "properties/core/kappa_rot_star",
                "properties/particle_specific/metallicity_star_mass_weighted",
                "properties/particle_specific/age_star_mass_weighted",
                "properties/photometry/luminosity_fir",
                "properties/photometry/mag_abs_v",
                "properties/photometry/mag_abs_nodust_v",
                "properties/photometry/mag_app_v",
                "properties/photometry/mag_app_nodust_v",
                "properties/photometry/beta",
                "properties/photometry/beta_nodust",
            ],
        ),
        (
            "membership/bh_lengths",
            [
                "properties/core/radius_r20_bh",
                "properties/core/radius_half_mass_bh",
                "properties/core/radius_r80_bh",
                "properties/core/velocity_dispersion_bh",
                "properties/core/L_bh",
                "properties/core/inertia_tensor_bh",
                "properties/core/L_azimuth_bh",
                "properties/core/L_elevation_bh",
                "properties/core/BoverT_bh",
                "properties/core/kappa_rot_bh",
                "properties/particle_specific/smbh_mdot",
                "properties/particle_specific/smbh_fedd",
                "properties/particle_specific/smbh_mass",
            ],
        ),
    ],
}

# these can be zero, but if they are zero the corresponding group should be empty
ZERO_WHEN_EMPTY = {
    "halo_data": [
        (
            "membership/gas_lengths",
            [
                "properties/core/mass_gas",
                "properties/particle_specific/mass_HI",
                "properties/particle_specific/mass_H2",
                "properties/particle_specific/mass_cgm",
                "properties/particle_specific/mass_gas_cold",
                "properties/particle_specific/mass_gas_hot",
            ],
        ),
        ("membership/star_lengths", ["properties/core/mass_star"]),
        ("membership/dm_lengths", ["properties/core/mass_dm"]),
        (
            "membership/bh_lengths",
            [
                "properties/core/mass_bh",
            ],
        ),
    ],
    "galaxy_data": [
        (
            "membership/gas_lengths",
            [
                "properties/core/mass_gas",
                "properties/particle_specific/mass_HI",
                "properties/particle_specific/mass_H2",
                "properties/particle_specific/mass_gas_cold",
                "properties/particle_specific/mass_gas_hot",
            ],
        ),
        ("membership/star_lengths", ["properties/core/mass_star"]),
        (
            "membership/bh_lengths",
            [
                "properties/core/mass_bh",
            ],
        ),
    ],
}

# these can be nan (zero metallicity/sfr), but if a large percentage is, this is worth flagging
SOFT_NAN = [
    "properties/particle_specific/metallicity_gas_sfr_weighted",
    "properties/particle_specific/metallicity_gas_mass_weighted_cgm",
    "properties/particle_specific/metallicity_gas_temperature_weighted_cgm",
    "properties/particle_specific/temperature_gas_mass_weighted_cgm",
    "properties/particle_specific/temperature_gas_metal_weighted_cgm",
    "properties/particle_specific/age_star_metal_weighted",
    "properties/core/r200m",
    "properties/core/velocity_circular",
    "properties/core/spin_param",
    "properties/core/temperature_virial",
    "properties/core/r200c",
    "properties/core/r500c",
    "properties/core/r2500c",
    "properties/core/m200c",
    "properties/core/m500c",
    "properties/core/m2500c",
    "properties/core/vmax",
    "properties/core/rmax",
]
